import { useEffect, useState } from "react";
import { FiBriefcase, FiCalendar, FiFileText } from "react-icons/fi";
import jobService from "../../services/jobService";

export default function JobApplications() {
  const [applications, setApplications] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { jobService.getMyJobApplications().then((response) => setApplications(response?.data?.applications || [])).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)); }, []);
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-[#E87524]">Dashboard</p><h1 className="mt-1 text-2xl font-bold text-[#102A43]">Job Applications</h1><p className="mt-2 text-sm text-gray-500">Track every application and its current review status.</p></div>{error && <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading ? <div className="rounded-2xl bg-white p-10 text-center text-sm text-gray-500">Loading applications...</div> : <div className="space-y-4">{applications.map((application) => <article key={application._id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-orange-50 text-[#E87524]"><FiBriefcase size={20}/></div><div><h3 className="font-bold text-[#102A43]">{application.job?.title || "Direct application"}</h3><p className="mt-1 text-sm text-gray-500">{application.job?.department || "Laxmi Construction"}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-gray-400"><span className="flex items-center gap-1.5"><FiCalendar/>Applied {new Date(application.createdAt).toLocaleDateString("en-IN")}</span><span className="flex items-center gap-1.5"><FiFileText/>{application._id}</span></div></div></div><Status status={application.status}/></div></article>)}{!applications.length && <div className="rounded-2xl bg-white p-10 text-center text-sm text-gray-500">You have not applied for any jobs yet.</div>}</div>}</div>;
}
function Status({ status }) { const labels = { applied: "Applied", "under-review": "Under review", shortlisted: "Shortlisted", selected: "Selected", rejected: "Rejected" }; const styles = { applied: "bg-blue-50 text-blue-700", "under-review": "bg-blue-50 text-blue-700", shortlisted: "bg-orange-50 text-orange-700", selected: "bg-green-50 text-green-700", rejected: "bg-red-50 text-red-700" }; return <span className={`w-fit rounded-full px-3 py-1.5 text-xs font-semibold ${styles[status] || "bg-gray-50 text-gray-600"}`}>{labels[status] || status}</span>; }
