import { useEffect, useMemo, useState } from "react";
import { FiSearch, FiFilter } from "react-icons/fi";
import ProjectGrid from "../../components/projects/ProjectGrid";
import projectService from "../../services/projectService";

export default function MyProjects() {
  const [projects, setProjects] = useState([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { projectService.getMyProjects().then((response) => setProjects(response?.data?.projects || [])).catch((requestError) => setError(requestError.message || "Unable to load assigned projects.")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => projects.filter((project) => `${project.title} ${project.location}`.toLowerCase().includes(search.toLowerCase()) && (!status || project.status === status)), [projects, search, status]);
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-[#E87524]">Dashboard</p><h1 className="mt-1 text-2xl font-bold text-[#102A43]">Assigned Projects</h1><p className="mt-2 text-sm text-gray-500">Projects appear here only when Laxmi Construction assigns work to your account.</p></div><div className="flex flex-col gap-3 rounded-2xl border border-gray-100 bg-white p-4 shadow-sm md:flex-row"><div className="relative flex-1"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search assigned projects..." className="h-11 w-full rounded-xl border border-gray-200 bg-gray-50 pl-11 pr-4 text-sm"/></div><div className="relative"><FiFilter className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-gray-400"/><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 min-w-[170px] rounded-xl border border-gray-200 bg-gray-50 pl-10 pr-4 text-sm"><option value="">All statuses</option><option value="planning">Planning</option><option value="ongoing">Ongoing</option><option value="completed">Completed</option><option value="on-hold">On hold</option></select></div></div>{error && <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<ProjectGrid projects={filtered} loading={loading}/></div>;
}
