import { useEffect, useState } from "react";
import { ActivityIndicator, ImageBackground, Pressable, ScrollView, StatusBar, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useAuth } from "../context/AuthContext";
import { COLORS } from "../components/AuthUI";

const services = [
  { name: "Residential", image: require("../images/construction-service.jpg") },
  { name: "Commercial", image: require("../images/consultancy-service.jpg") },
  { name: "Renovation", image: require("../images/renovation-service.jpg") },
  { name: "Skilled labour", image: require("../images/labour-service.jpg") },
];
export default function HomeScreen() {
  const { session, ready, signOut } = useAuth(); const [signingOut, setSigningOut] = useState(false);
  useEffect(() => { if (ready && !session) router.replace("/welcome"); }, [ready, session]);
  if (!ready || !session) return <View style={styles.loading}><ActivityIndicator color={COLORS.orange} size="large" /></View>;
  return <View style={styles.screen}><StatusBar barStyle="dark-content" backgroundColor="#FFF" /><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.small}>LAXMI CONSTRUCTION</Text><Text style={styles.greeting}>Hello, {session.user?.name?.split(" ")[0] || "Builder"} 👋</Text></View><Pressable onPress={async () => { setSigningOut(true); await signOut(); router.replace("/welcome"); }} style={styles.avatar}><Text style={styles.avatarText}>{session.user?.name?.[0]?.toUpperCase() || "L"}</Text></Pressable></View>
    <ImageBackground source={require("../images/hero-construction.jpg")} resizeMode="cover" style={styles.hero} imageStyle={styles.heroImage}><View style={styles.heroShade} /><Text style={styles.heroEyebrow}>PLAN • BUILD • GROW</Text><Text style={styles.heroTitle}>Build your dream{ "\n"}with confidence.</Text><Text style={styles.heroCopy}>Professional construction support, all in one place.</Text><Pressable style={styles.heroButton} onPress={() => router.push("/contact")}><Text style={styles.heroButtonText}>Request a service  →</Text></Pressable></ImageBackground>
    <View style={styles.row}><Text style={styles.section}>Explore services</Text><Pressable onPress={() => router.push("/services")}><Text style={styles.viewAll}>View all</Text></Pressable></View>
    <View style={styles.grid}>{services.map((service) => <Pressable key={service.name} onPress={() => router.push("/services")} style={styles.service}><ImageBackground source={service.image} resizeMode="cover" style={styles.servicePhoto} imageStyle={styles.serviceImage}><View style={styles.serviceShade} /><Text style={styles.serviceName}>{service.name}</Text></ImageBackground></Pressable>)}</View>
    <Text style={styles.section}>Your Laxmi workspace</Text>
    <Pressable style={styles.workspace} onPress={() => router.push("/projects")}><Text style={styles.workspaceIcon}>▤</Text><View style={{ flex: 1 }}><Text style={styles.workspaceTitle}>Project portfolio</Text><Text style={styles.workspaceCopy}>Browse completed work and get inspired.</Text></View><Text style={styles.chevron}>›</Text></Pressable>
    <Pressable style={styles.workspace} onPress={() => router.push("/contact")}><Text style={styles.workspaceIcon}>✉</Text><View style={{ flex: 1 }}><Text style={styles.workspaceTitle}>Talk to our team</Text><Text style={styles.workspaceCopy}>Tell us what you are planning.</Text></View><Text style={styles.chevron}>›</Text></Pressable>
    <Pressable onPress={async () => { setSigningOut(true); await signOut(); router.replace("/welcome"); }} style={styles.signOut} disabled={signingOut}><Text style={styles.signOutText}>{signingOut ? "Signing out…" : "Sign out"}</Text></Pressable>
  </ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#F8FAFC" }, loading: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#FFF" }, content: { padding: 20, paddingTop: 52, paddingBottom: 40 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }, small: { color: COLORS.orange, fontSize: 10, fontWeight: "900", letterSpacing: 1.7 }, greeting: { color: COLORS.navy, fontSize: 22, fontWeight: "900", marginTop: 4 }, avatar: { height: 44, width: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.navy }, avatarText: { color: "#FFF", fontWeight: "900", fontSize: 18 }, hero: { minHeight: 280, borderRadius: 24, padding: 22, justifyContent: "center", overflow: "hidden", marginBottom: 26 }, heroImage: { borderRadius: 24 }, heroShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(4,30,50,0.68)" }, heroEyebrow: { color: "#FFC087", fontSize: 11, fontWeight: "900", letterSpacing: 1.4 }, heroTitle: { color: "#FFF", fontSize: 28, lineHeight: 34, fontWeight: "900", marginTop: 10 }, heroCopy: { color: "#E7EDF3", fontSize: 14, lineHeight: 20, marginTop: 7 }, heroButton: { alignSelf: "flex-start", borderRadius: 13, backgroundColor: COLORS.orange, paddingHorizontal: 15, paddingVertical: 12, marginTop: 17 }, heroButtonText: { color: "#FFF", fontSize: 13, fontWeight: "800" }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }, section: { color: COLORS.navy, fontSize: 19, fontWeight: "900", marginBottom: 12 }, viewAll: { color: COLORS.orange, fontWeight: "800", marginBottom: 12 }, grid: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -5, marginBottom: 18 }, service: { width: "50%", padding: 5 }, servicePhoto: { height: 128, justifyContent: "flex-end", padding: 13, overflow: "hidden" }, serviceImage: { borderRadius: 18 }, serviceShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(4,30,50,0.36)" }, serviceName: { color: "#FFF", fontSize: 15, fontWeight: "900" }, workspace: { flexDirection: "row", alignItems: "center", padding: 15, backgroundColor: "#FFF", borderRadius: 17, marginBottom: 10, elevation: 1 }, workspaceIcon: { color: COLORS.orange, fontSize: 23, width: 42 }, workspaceTitle: { color: COLORS.navy, fontSize: 15, fontWeight: "800" }, workspaceCopy: { color: COLORS.muted, fontSize: 12, marginTop: 4 }, chevron: { fontSize: 27, color: COLORS.orange }, signOut: { paddingVertical: 16, alignItems: "center" }, signOutText: { color: COLORS.muted, fontWeight: "700" } });
