import { useEffect, useState } from "react";
import { ActivityIndicator, ImageBackground, Pressable, ScrollView, StatusBar, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useAuth } from "../context/AuthContext";
import { COLORS } from "../components/AuthUI";

const shortcuts = [
  { title: "Services", copy: "Construction, renovation & consultancy", route: "/services", icon: "⌂" },
  { title: "Request a service", copy: "Tell us what your project needs", route: "/service-request", icon: "＋" },
  { title: "Skilled labour", copy: "Find and request experienced workers", route: "/labour", icon: "⚒" },
  { title: "My requests", copy: "Follow your service requests", route: "/service-requests", icon: "◷" },
  { title: "Projects", copy: "Explore our construction work", route: "/projects", icon: "▤" },
  { title: "Careers", copy: "Open jobs and career applications", route: "/careers", icon: "▣" },
  { title: "My applications", copy: "Check your application status", route: "/my-applications", icon: "✓" },
  { title: "My account", copy: "Profile, settings and notifications", route: "/dashboard", icon: "●" },
];
export default function HomeScreen() {
  const { session, ready, signOut } = useAuth(); const [signingOut, setSigningOut] = useState(false);
  useEffect(() => { if (ready && !session) router.replace("/welcome"); }, [ready, session]);
  if (!ready || !session) return <View style={styles.loading}><ActivityIndicator color={COLORS.orange} size="large" /></View>;
  return <View style={styles.screen}><StatusBar barStyle="dark-content" backgroundColor="#FFF" /><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.small}>LAXMI CONSTRUCTION</Text><Text style={styles.greeting}>Hello, {session.user?.name?.split(" ")[0] || "Builder"} 👋</Text></View><Pressable onPress={() => router.push("/profile")} style={styles.avatar}><Text style={styles.avatarText}>{session.user?.name?.[0]?.toUpperCase() || "L"}</Text></Pressable></View>
    <ImageBackground source={require("../images/hero-construction.jpg")} resizeMode="cover" style={styles.hero} imageStyle={styles.heroImage}><View style={styles.heroShade} /><Text style={styles.heroEyebrow}>PLAN • BUILD • GROW</Text><Text style={styles.heroTitle}>Build your dream{"\n"}with confidence.</Text><Text style={styles.heroCopy}>Professional construction support, all in one place.</Text><Pressable style={styles.heroButton} onPress={() => router.push("/service-request")}><Text style={styles.heroButtonText}>Request a service  →</Text></Pressable></ImageBackground>
    <Text style={styles.section}>Your construction workspace</Text><View style={styles.grid}>{shortcuts.map((item) => <Pressable key={item.title} onPress={() => router.push(item.route)} style={styles.service}><View style={styles.icon}><Text style={styles.iconText}>{item.icon}</Text></View><Text style={styles.serviceName}>{item.title}</Text><Text style={styles.serviceCopy}>{item.copy}</Text></Pressable>)}</View>
    {session.user?.role === "admin" ? <Pressable onPress={() => router.push("/admin")} style={styles.admin}><Text style={styles.adminTitle}>Open admin console →</Text><Text style={styles.adminCopy}>Manage requests, projects, jobs and customers.</Text></Pressable> : null}
    <Pressable onPress={async () => { setSigningOut(true); await signOut(); router.replace("/welcome"); }} style={styles.signOut} disabled={signingOut}><Text style={styles.signOutText}>{signingOut ? "Signing out…" : "Sign out"}</Text></Pressable>
  </ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#F8FAFC" }, loading: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#FFF" }, content: { padding: 18, paddingTop: 44, paddingBottom: 40 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }, small: { color: COLORS.orange, fontSize: 10, fontWeight: "900", letterSpacing: 1.7 }, greeting: { color: COLORS.navy, fontSize: 22, fontWeight: "900", marginTop: 4 }, avatar: { height: 44, width: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.navy }, avatarText: { color: "#FFF", fontWeight: "900", fontSize: 18 }, hero: { minHeight: 260, borderRadius: 24, padding: 20, justifyContent: "center", overflow: "hidden", marginBottom: 22 }, heroImage: { borderRadius: 24 }, heroShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(4,30,50,0.68)" }, heroEyebrow: { color: "#FFC087", fontSize: 11, fontWeight: "900", letterSpacing: 1.4 }, heroTitle: { color: "#FFF", fontSize: 27, lineHeight: 33, fontWeight: "900", marginTop: 9 }, heroCopy: { color: "#E7EDF3", fontSize: 13, lineHeight: 19, marginTop: 6 }, heroButton: { alignSelf: "flex-start", borderRadius: 13, backgroundColor: COLORS.orange, paddingHorizontal: 14, paddingVertical: 11, marginTop: 15 }, heroButtonText: { color: "#FFF", fontSize: 13, fontWeight: "800" }, section: { color: COLORS.navy, fontSize: 18, fontWeight: "900", marginBottom: 11 }, grid: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -5 }, service: { width: "50%", padding: 13, marginBottom: 10, backgroundColor: "#FFF", borderRadius: 16, borderWidth: 1, borderColor: "#E9EEF3", minHeight: 142 }, icon: { width: 34, height: 34, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF1E8", marginBottom: 8 }, iconText: { color: COLORS.orange, fontSize: 19, fontWeight: "900" }, serviceName: { color: COLORS.navy, fontSize: 14, fontWeight: "800" }, serviceCopy: { color: "#718096", fontSize: 11, lineHeight: 15, marginTop: 4 }, admin: { backgroundColor: COLORS.navy, borderRadius: 16, padding: 16, marginTop: 8 }, adminTitle: { color: "#FFF", fontSize: 15, fontWeight: "900" }, adminCopy: { color: "#CED9E4", fontSize: 12, marginTop: 5 }, signOut: { paddingVertical: 16, alignItems: "center" }, signOutText: { color: "#718096", fontWeight: "700" } });
