import { useEffect, useMemo, useState } from "react";
import { Text, View } from "react-native";
import { api } from "../config/api";
import { PortalScreen, FormField, Button, Notice, DataCard, Loading, Empty, SectionTitle, COLORS } from "../components/PortalUI";
import { useRequireAuth } from "../hooks/useRequireAuth";
export default function LabourScreen() {
  const { session } = useRequireAuth(); const [workers, setWorkers] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [skill, setSkill] = useState(""); const [selected, setSelected] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [form, setForm] = useState({ customerName: session?.user?.name || "", phone: session?.user?.phone || "", location: "", workersRequired: "1", startDate: "", duration: "", requirements: "" });
  useEffect(() => { api.getLabour().then((r) => setWorkers(r.data?.labour || [])).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const matches = useMemo(() => workers.filter((w) => w.availability !== "unavailable" && `${w.name} ${w.skill} ${w.location}`.toLowerCase().includes(`${search} ${skill}`.trim().toLowerCase())), [workers, search, skill]);
  const set = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  const requestWorker = async () => {
    setError(""); setSuccess("");
    if (!form.customerName.trim() || !form.phone.trim() || !form.location.trim() || !form.startDate.trim() || Number(form.workersRequired) < 1) return setError("Enter your name, phone, project location, worker count and start date.");
    if (!/^[6-9]\d{9}$/.test(form.phone.replace(/\s/g, ""))) return setError("Enter a valid 10-digit Indian phone number.");
    setBusy(true); try { await api.createLabourRequest({ labourId: selected._id, labourName: selected.name, skill: selected.skill, ...form, phone: form.phone.replace(/\s/g, ""), workersRequired: Number(form.workersRequired) }); setSuccess("Worker request submitted. Track it from Labour Requests."); setSelected(null); }
    catch (e) { setError(e.message); } finally { setBusy(false); }
  };
  return <PortalScreen title="Find skilled labour"><Text style={{ color: "#65758A", lineHeight: 20 }}>Browse available workers and request the team your project needs.</Text><FormField label="Search workers" value={search} onChangeText={setSearch} placeholder="Name, skill or location" /><FormField label="Filter by skill" value={skill} onChangeText={setSkill} placeholder="Mason, electrician, painter…" /><Notice message={error} /><Notice type="success" message={success} /><SectionTitle>Available professionals</SectionTitle>{loading ? <Loading /> : matches.length ? matches.map((worker) => <DataCard key={worker._id}><View style={{ flexDirection: "row", justifyContent: "space-between", gap: 10 }}><View style={{ flex: 1 }}><Text style={{ color: COLORS.navy, fontSize: 16, fontWeight: "900" }}>{worker.name}</Text><Text style={{ color: COLORS.orange, fontWeight: "800", marginTop: 3 }}>{worker.skill}{worker.experience ? ` · ${worker.experience} yrs` : ""}</Text></View><Text style={{ color: "#2F855A", fontWeight: "800", fontSize: 11 }}>{worker.availability || "available"}</Text></View><Text style={{ color: "#65758A" }}>{worker.location || "Location available on request"}{worker.dailyRate ? ` · ?${worker.dailyRate}/day` : ""}</Text>{worker.description ? <Text style={{ color: "#475569", lineHeight: 20 }}>{worker.description}</Text> : null}<Button title={selected?._id === worker._id ? "Selected" : "Request this worker"} onPress={() => { setSelected(worker); setForm((f) => ({ ...f, customerName: f.customerName || session?.user?.name || "", phone: f.phone || session?.user?.phone || "" })); }} /></DataCard>) : <Empty>No workers match those filters.</Empty>}{selected ? <DataCard><Text style={{ color: COLORS.navy, fontSize: 18, fontWeight: "900" }}>Request {selected.name}</Text><FormField label="Your name" value={form.customerName} onChangeText={(v) => set("customerName", v)} /><FormField label="Phone number" value={form.phone} onChangeText={(v) => set("phone", v.replace(/\D/g, "").slice(0, 10))} keyboardType="phone-pad" /><FormField label="Project location" value={form.location} onChangeText={(v) => set("location", v)} /><FormField label="Workers required" value={form.workersRequired} onChangeText={(v) => set("workersRequired", v.replace(/\D/g, ""))} keyboardType="number-pad" /><FormField label="Start date (YYYY-MM-DD)" value={form.startDate} onChangeText={(v) => set("startDate", v)} placeholder="2026-10-15" /><FormField label="Expected duration" value={form.duration} onChangeText={(v) => set("duration", v)} placeholder="e.g. 2 weeks" /><FormField label="Requirements" value={form.requirements} onChangeText={(v) => set("requirements", v)} multiline /><Button title={busy ? "Submitting…" : "Submit labour request"} onPress={requestWorker} disabled={busy} /><Button title="Close" variant="outline" onPress={() => setSelected(null)} /></DataCard> : null}</PortalScreen>;
}


