import { useState } from "react";
import { Alert, Switch, Text, View } from "react-native";
import { router } from "expo-router";
import { api } from "../config/api";
import { useAuth } from "../context/AuthContext";
import { useRequireAuth } from "../hooks/useRequireAuth";
import { PortalScreen, FormField, Button, DataCard, Notice, COLORS } from "../components/PortalUI";
const defaults = { email: true, projectUpdates: true, serviceRequests: true, jobUpdates: true };
export default function SettingsScreen() {
  const { session, signOut } = useAuth(); useRequireAuth();
  const [preferences, setPreferences] = useState({ ...defaults, ...(session?.user?.notificationPreferences || {}) });
  const [currentPassword, setCurrent] = useState(""); const [newPassword, setNew] = useState(""); const [confirm, setConfirm] = useState("");
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const savePreferences = async () => { setError(""); try { await api.updateNotificationPreferences(preferences); setMessage("Notification preferences saved."); } catch (e) { setError(e.message); } };
  const changePassword = async () => { setError(""); setMessage(""); if (!currentPassword || newPassword.length < 6) return setError("Enter your current password and a new password with at least 6 characters."); if (newPassword !== confirm) return setError("The new passwords do not match."); setBusy(true); try { await api.changePassword({ currentPassword, newPassword }); setCurrent(""); setNew(""); setConfirm(""); setMessage("Password changed successfully."); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const deleteAccount = () => Alert.alert("Delete account?", "This permanently removes your account and notifications.", [{ text: "Keep account", style: "cancel" }, { text: "Delete account", style: "destructive", onPress: async () => { try { await api.deleteAccount(); await signOut(); router.replace("/welcome"); } catch (e) { setError(e.message); } } }]);
  return <PortalScreen title="Settings"><Notice message={error} /><Notice type="success" message={message} /><DataCard><Text style={{ color: COLORS.navy, fontWeight: "900", fontSize: 18 }}>Change password</Text><FormField label="Current password" value={currentPassword} onChangeText={setCurrent} secureTextEntry autoCapitalize="none" /><FormField label="New password" value={newPassword} onChangeText={setNew} secureTextEntry autoCapitalize="none" /><FormField label="Confirm new password" value={confirm} onChangeText={setConfirm} secureTextEntry autoCapitalize="none" /><Button title={busy ? "Updating…" : "Update password"} onPress={changePassword} disabled={busy} /></DataCard><DataCard><Text style={{ color: COLORS.navy, fontWeight: "900", fontSize: 18 }}>Notifications</Text>{[["email", "Email notifications"], ["projectUpdates", "Project updates"], ["serviceRequests", "Service request updates"], ["jobUpdates", "Job application updates"]].map(([key, label]) => <View key={key} style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 9 }}><Text style={{ color: "#40536A", flex: 1 }}>{label}</Text><Switch value={Boolean(preferences[key])} onValueChange={(value) => setPreferences((old) => ({ ...old, [key]: value }))} trackColor={{ true: COLORS.orange }} /></View>)}<Button variant="outline" title="Save notification preferences" onPress={savePreferences} /></DataCard><DataCard><Text style={{ color: COLORS.navy, fontWeight: "900", fontSize: 18 }}>Privacy & security</Text><Text style={{ color: "#66778A", lineHeight: 20 }}>Your account information is used to provide project, service and communication features.</Text><Button variant="danger" title="Delete my account" onPress={deleteAccount} /></DataCard></PortalScreen>;
}
