import { useState } from "react";
import { Image, ImageBackground, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { COLORS } from "../components/AuthUI";
const slides = [
  { title: "Build Your Dream", accent: "With Confidence", copy: "Professional construction services to turn your vision into reality.", image: require("../images/construction-service.jpg"), cards: ["Residential construction", "Commercial construction", "Renovation & interiors", "Civil work & more"] },
  { title: "Everything You Need,", accent: "In One Place", copy: "Construction, consultancy, skilled labour and project support at your fingertips.", image: require("../images/labour-service.jpg"), cards: ["Find skilled labour", "Expert consultancy", "Manage projects", "Quality trusted service"] },
];
export default function WelcomeScreen() {
  const [page, setPage] = useState(0); const slide = slides[page];
  return <View style={styles.screen}><ImageBackground source={slide.image} resizeMode="cover" style={styles.photo}><View style={styles.wash} /><View style={styles.top}><Image source={require("../images/logo1.png")} style={styles.logo} resizeMode="contain" /><Pressable onPress={() => router.push("/login")}><Text style={styles.skip}>Skip</Text></Pressable></View><View style={styles.copy}><Text style={styles.title}>{slide.title}{"\n"}<Text style={styles.accent}>{slide.accent}</Text></Text><Text style={styles.description}>{slide.copy}</Text></View><View style={styles.cards}>{slide.cards.map((item, index) => <View style={styles.card} key={item}><View style={[styles.icon, index % 2 ? styles.iconBlue : null]}><Text style={styles.iconText}>{["⌂", "▥", "▰", "◆"][index]}</Text></View><Text style={styles.cardText}>{item}</Text></View>)}</View></ImageBackground><View style={styles.footer}><View style={styles.dots}>{slides.map((_, i) => <View key={i} style={[styles.dot, i === page && styles.dotActive]} />)}</View><View style={styles.actions}><Pressable onPress={() => router.push("/login")}><Text style={styles.skip}>Sign in</Text></Pressable><Pressable style={styles.next} onPress={() => page === 0 ? setPage(1) : router.push("/register")}><Text style={styles.nextText}>{page === 0 ? "Next" : "Get Started"}  →</Text></Pressable></View></View></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#FFF" }, photo: { flex: 1, paddingTop: 48, paddingHorizontal: 24 }, wash: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(255,255,255,0.68)" }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, logo: { width: 120, height: 76 }, skip: { color: COLORS.navy, fontWeight: "700", fontSize: 16 }, copy: { marginTop: 10, marginBottom: 20, maxWidth: 330 }, title: { color: COLORS.navy, fontSize: 31, lineHeight: 37, fontWeight: "900" }, accent: { color: COLORS.orange }, description: { color: COLORS.muted, fontSize: 15, lineHeight: 22, marginTop: 8 }, cards: { flexDirection: "row", flexWrap: "wrap", backgroundColor: "rgba(255,255,255,0.94)", borderRadius: 24, padding: 12, marginTop: "auto", marginBottom: 18, elevation: 4 }, card: { width: "50%", padding: 8, minHeight: 104, justifyContent: "center" }, icon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFF0E5", alignItems: "center", justifyContent: "center", marginBottom: 8 }, iconBlue: { backgroundColor: "#E7F2FA" }, iconText: { color: COLORS.orange, fontSize: 23, fontWeight: "900" }, cardText: { color: COLORS.ink, fontSize: 13, fontWeight: "700" }, footer: { paddingHorizontal: 26, paddingTop: 12, paddingBottom: 28 }, dots: { flexDirection: "row", justifyContent: "center", gap: 10, marginBottom: 19 }, dot: { width: 11, height: 11, borderRadius: 8, backgroundColor: "#D7DCE1" }, dotActive: { backgroundColor: COLORS.orange, width: 26 }, actions: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, next: { minWidth: 170, alignItems: "center", backgroundColor: COLORS.orange, paddingVertical: 16, borderRadius: 30 }, nextText: { color: "#FFF", fontSize: 16, fontWeight: "800" } });
