import { useEffect, useState } from "react";
import { Text, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import { router } from "expo-router";
import { api } from "../../config/api";
import { useAuth } from "../../context/AuthContext";
import Screen from "../../components/Screen";
import PageHeader from "../../components/PageHeader";
import { FormField, Button, DataCard, Loading, Empty, Notice, COLORS } from "../../components/PortalUI";
const resumeTypes = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
export default function CareersScreen() {
  const { session } = useAuth(); const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(""); const [resume, setResume] = useState(null); const [form, setForm] = useState({ customPosition: "", phone: session?.user?.phone || "", coverLetter: "" });
  useEffect(() => { api.getJobs().then((r) => setJobs(r.data?.jobs || [])).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const set = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  const chooseResume = async () => { const result = await DocumentPicker.getDocumentAsync({ type: resumeTypes, copyToCacheDirectory: true }); if (result.canceled) return; const file = result.assets?.[0]; if (!file) return; if (file.size > 5 * 1024 * 1024) return setError("Resume must be no larger than 5 MB."); setResume(file); setError(""); };
  const submit = async () => { setError(""); if (!form.customPosition.trim() || !form.phone.trim() || !form.coverLetter.trim()) return setError("Enter the position you want, phone number and a short cover letter."); if (!/^\d{10}$/.test(form.phone.replace(/\s/g, ""))) return setError("Enter a valid 10-digit phone number."); if (!session) return router.push({ pathname: "/login", params: { next: "/careers" } }); const data = new FormData(); data.append("customPosition", form.customPosition.trim()); data.append("coverLetter", form.coverLetter.trim()); data.append("phone", form.phone.replace(/\s/g, "")); if (resume) data.append("resume", { uri: resume.uri, name: resume.name, type: resume.mimeType || "application/pdf" }); setBusy(true); try { await api.applyGeneral(data); setFeedback("Your open application has been submitted."); setShowForm(false); setForm({ customPosition: "", phone: session.user?.phone || "", coverLetter: "" }); setResume(null); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <Screen><PageHeader eyebrow="Careers" title="Build your career with us" description="Explore current vacancies or send an open application if the right role is not listed." /><Button title="Send an open application" onPress={() => session ? setShowForm((v) => !v) : router.push({ pathname: "/login", params: { next: "/careers" } })} /><Notice type="success" message={feedback} /><Notice message={error} />{showForm ? <DataCard><Text style={{ color: COLORS.navy, fontSize: 18, fontWeight: "900" }}>Open application</Text><FormField label="Desired position" value={form.customPosition} onChangeText={(v) => set("customPosition", v)} placeholder="e.g. Site Engineer" /><FormField label="Phone number" value={form.phone} onChangeText={(v) => set("phone", v.replace(/\D/g, "").slice(0, 10))} keyboardType="phone-pad" /><FormField label="Cover letter" value={form.coverLetter} onChangeText={(v) => set("coverLetter", v)} multiline /><Button variant="outline" title={resume?.name || "Attach resume (optional)"} onPress={chooseResume} /><Button title={busy ? "Submitting…" : "Submit application"} onPress={submit} disabled={busy} /></DataCard> : null}<View style={{ height: 8 }} /><Text style={{ color: COLORS.navy, fontWeight: "900", fontSize: 20 }}>Open positions</Text>{loading ? <Loading /> : jobs.length ? jobs.map((job) => <DataCard key={job._id}><Text style={{ color: COLORS.navy, fontSize: 18, fontWeight: "900" }}>{job.title}</Text><Text style={{ color: COLORS.orange, fontWeight: "700" }}>{job.department || "Laxmi Construction"}</Text><Text style={{ color: "#66778A" }}>{job.location || "Location to be confirmed"} · {job.type || "Full Time"} · {job.experience || "Fresher"}</Text><Button title="View role and apply ?" onPress={() => router.push(`/careers/${job._id}`)} /></DataCard>) : <Empty>No open positions right now.</Empty>}<Button variant="outline" title="My job applications" onPress={() => session ? router.push("/my-applications") : router.push("/login")} /></Screen>;
}

