import { ActivityIndicator, ImageBackground, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

export const COLORS = { navy: "#092B47", orange: "#F45A0A", ink: "#132C45", muted: "#65758A", line: "#DCE5ED", pale: "#FFF7F0", white: "#FFFFFF" };
export function AuthShell({ children, image = require("../images/hero-construction.jpg") }) {
  return <View style={styles.root}><ImageBackground source={image} resizeMode="cover" style={styles.backdrop}><View style={styles.tint} /></ImageBackground><KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.scroll}>{children}</ScrollView></KeyboardAvoidingView></View>;
}
export function Brand({ compact = false }) { return <View style={[styles.brand, compact && styles.brandCompact]}><Text style={styles.brandTop}>LAXMI</Text><Text style={styles.brandBottom}>CONSTRUCTION</Text><Text style={styles.tagline}>BUILD TODAY. BETTER TOMORROW.</Text></View>; }
export function Field({ label, ...props }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={styles.inputWrap}><TextInput placeholderTextColor="#8A9AAF" style={styles.input} {...props} /></View></View>; }
export function PrimaryButton({ title, onPress, loading, disabled }) { return <Pressable disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [styles.button, (pressed || disabled || loading) && { opacity: 0.72 }]}><Text style={styles.buttonText}>{loading ? "Please wait..." : title}</Text>{loading ? <ActivityIndicator color="#FFF" /> : <Text style={styles.buttonArrow}>›</Text>}</Pressable>; }
export function ErrorNote({ children }) { return children ? <View style={styles.error}><Text style={styles.errorText}>{children}</Text></View> : null; }
export function Caption({ children }) { return <Text style={styles.caption}>{children}</Text>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: "#FFF" }, backdrop: { position: "absolute", top: 0, left: 0, right: 0, height: "56%" }, tint: { flex: 1, backgroundColor: "rgba(255,255,255,0.80)" }, keyboard: { flex: 1 }, scroll: { flexGrow: 1, paddingTop: 46, paddingHorizontal: 26, paddingBottom: 32, justifyContent: "center" }, brand: { alignItems: "center", marginBottom: 30 }, brandCompact: { marginBottom: 22 }, brandTop: { color: COLORS.navy, fontWeight: "900", fontSize: 40, letterSpacing: 4 }, brandBottom: { color: COLORS.orange, fontWeight: "900", fontSize: 16, letterSpacing: 5, marginTop: -4 }, tagline: { color: COLORS.navy, fontSize: 8, fontWeight: "800", letterSpacing: 2.4, marginTop: 6 }, field: { marginBottom: 14 }, label: { color: COLORS.ink, fontWeight: "700", fontSize: 13, marginBottom: 7 }, inputWrap: { minHeight: 52, borderRadius: 15, borderWidth: 1, borderColor: COLORS.line, backgroundColor: "rgba(255,255,255,0.94)", justifyContent: "center", paddingHorizontal: 15 }, input: { color: COLORS.ink, fontSize: 16, paddingVertical: 12 }, button: { height: 54, backgroundColor: COLORS.orange, borderRadius: 17, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 12, marginTop: 6 }, buttonText: { color: "#FFF", fontSize: 16, fontWeight: "800" }, buttonArrow: { color: "#FFF", fontSize: 27, lineHeight: 30, marginTop: -3 }, error: { borderRadius: 12, backgroundColor: "#FFF1F0", borderColor: "#FFD4D0", borderWidth: 1, padding: 12, marginBottom: 12 }, errorText: { color: "#A7281A", fontSize: 13, lineHeight: 19 }, caption: { color: COLORS.muted, fontSize: 14, lineHeight: 21, textAlign: "center" } });
