import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { COLORS } from "./AuthUI";

export { COLORS };
export function PortalScreen({ title, eyebrow = "LAXMI CONSTRUCTION", children, scroll = true }) {
  const content = scroll ? <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>{children}</ScrollView> : <View style={styles.content}>{children}</View>;
  return <SafeAreaView style={styles.safe}><View style={styles.topbar}><Pressable onPress={() => router.canGoBack() ? router.back() : router.replace("/home")} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><View style={{ flex: 1 }}><Text style={styles.eyebrow}>{eyebrow}</Text><Text numberOfLines={1} style={styles.pageTitle}>{title}</Text></View><Pressable onPress={() => router.push("/notifications")} style={styles.bell}><Text style={styles.bellText}>?</Text></Pressable></View>{content}</SafeAreaView>;
}
export function SectionTitle({ children, right }) { return <View style={styles.sectionRow}><Text style={styles.sectionTitle}>{children}</Text>{right}</View>; }
export function FormField({ label, value, onChangeText, multiline = false, style, ...props }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholderTextColor="#91A0B2" multiline={multiline} textAlignVertical={multiline ? "top" : "center"} style={[styles.input, multiline && styles.multiline, style]} {...props} /></View>; }
export function Button({ title, onPress, variant = "primary", disabled = false, style }) { return <Pressable onPress={onPress} disabled={disabled} style={({ pressed }) => [styles.button, styles[variant], pressed && { opacity: 0.75 }, disabled && { opacity: 0.5 }, style]}><Text style={[styles.buttonText, variant === "outline" && { color: COLORS.navy }]}>{title}</Text></Pressable>; }
export function Notice({ message, type = "error" }) { return message ? <View style={[styles.notice, type === "success" ? styles.success : null]}><Text style={[styles.noticeText, type === "success" ? styles.successText : null]}>{message}</Text></View> : null; }
export function Loading() { return <View style={styles.center}><ActivityIndicator color={COLORS.orange} size="large" /></View>; }
export function Empty({ children }) { return <View style={styles.empty}><Text style={styles.emptyText}>{children}</Text></View>; }
export function DataCard({ children, style }) { return <View style={[styles.card, style]}>{children}</View>; }
export function formatDate(value) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString("en-IN"); }
export function Badge({ children }) { return <View style={styles.badge}><Text style={styles.badgeText}>{String(children || "pending").replaceAll("-", " ")}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#F6F8FB" }, topbar: { minHeight: 68, backgroundColor: "#FFF", borderBottomColor: "#E9EEF3", borderBottomWidth: 1, flexDirection: "row", alignItems: "center", paddingHorizontal: 16, gap: 10 }, back: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#F4F6F9" }, backText: { color: COLORS.navy, fontSize: 30, lineHeight: 32, marginTop: -4 }, eyebrow: { color: COLORS.orange, fontSize: 9, fontWeight: "900", letterSpacing: 1.2 }, pageTitle: { color: COLORS.navy, fontSize: 17, fontWeight: "900", marginTop: 2 }, bell: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#FFF4EC" }, bellText: { color: COLORS.orange, fontSize: 20 }, content: { padding: 18, paddingBottom: 40, gap: 12 }, sectionRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 7 }, sectionTitle: { color: COLORS.navy, fontSize: 18, fontWeight: "900" }, field: { marginBottom: 10 }, label: { color: COLORS.ink, fontSize: 13, fontWeight: "700", marginBottom: 6 }, input: { minHeight: 48, borderRadius: 13, borderWidth: 1, borderColor: "#DCE4EC", color: COLORS.ink, backgroundColor: "#FFF", paddingHorizontal: 13, paddingVertical: 10, fontSize: 15 }, multiline: { minHeight: 100, paddingTop: 12 }, button: { minHeight: 46, borderRadius: 13, paddingVertical: 12, paddingHorizontal: 16, alignItems: "center", justifyContent: "center" }, primary: { backgroundColor: COLORS.orange }, outline: { backgroundColor: "#FFF", borderWidth: 1, borderColor: "#D7E0E8" }, danger: { backgroundColor: "#FFF1F0", borderWidth: 1, borderColor: "#F4D2CF" }, buttonText: { color: "#FFF", fontWeight: "800", fontSize: 14 }, notice: { backgroundColor: "#FFF1F0", borderColor: "#FFD7D3", borderWidth: 1, padding: 12, borderRadius: 12 }, noticeText: { color: "#A52A20", fontSize: 13, lineHeight: 19 }, success: { backgroundColor: "#EAF8EF", borderColor: "#C4ECD1" }, successText: { color: "#217345" }, center: { minHeight: 150, alignItems: "center", justifyContent: "center" }, empty: { backgroundColor: "#FFF", borderRadius: 16, padding: 24, alignItems: "center" }, emptyText: { color: "#718096", textAlign: "center", lineHeight: 21 }, card: { backgroundColor: "#FFF", borderRadius: 17, borderWidth: 1, borderColor: "#EBEFF3", padding: 16, gap: 8 }, badge: { alignSelf: "flex-start", backgroundColor: "#FFF2E9", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20 }, badgeText: { color: COLORS.orange, fontWeight: "800", fontSize: 11, textTransform: "capitalize" } });

