import { useEffect, useMemo, useState } from "react";
import { FiSearch, FiUser, FiMail, FiPhone, FiFileText } from "react-icons/fi";
import jobService from "../../services/jobService";

export default function JobApplications() {
  const [applications, setApplications] = useState([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const response = await jobService.getAllJobApplications(); setApplications(response?.data?.applications || []); } catch (requestError) { setError(requestError.message || "Unable to load applications."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => applications.filter((item) => `${item.applicantName || item.user?.name || ""} ${item.job?.title || ""}`.toLowerCase().includes(search.toLowerCase())), [applications, search]);
  const updateStatus = async (id, status) => { try { await jobService.updateApplicationStatus(id, status); await load(); } catch (requestError) { setError(requestError.message); } };
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-[#E87524]">Recruitment</p><h1 className="mt-1 text-2xl font-bold text-[#102A43]">Job Applications</h1><p className="mt-2 text-sm text-gray-500">Review applicants and update their status. Status changes notify the applicant by email.</p></div><div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><div className="relative max-w-lg"><FiSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={17}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search applicants or positions..." className="h-11 w-full rounded-xl border border-gray-200 bg-gray-50 pl-11 pr-4 text-sm"/></div></div>{error && <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="space-y-4">{loading ? <div className="rounded-2xl bg-white p-10 text-center text-sm text-gray-500">Loading applications...</div> : filtered.map((application) => { const id = application._id; return <article key={id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-orange-50 text-[#E87524]"><FiUser/></div><div><h3 className="font-bold text-[#102A43]">{application.applicantName || application.user?.name || "Applicant"}</h3><p className="mt-1 font-medium text-[#E87524]">{application.job?.title || "Direct application"}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-gray-500"><span className="flex items-center gap-1.5"><FiMail/>{application.email}</span><span className="flex items-center gap-1.5"><FiPhone/>{application.phone || "No phone"}</span><span className="flex items-center gap-1.5"><FiFileText/>Applied {new Date(application.createdAt).toLocaleDateString("en-IN")}</span></div></div></div><select value={application.status} onChange={(event) => updateStatus(id, event.target.value)} className="h-10 rounded-lg border border-gray-200 bg-gray-50 px-3 text-xs font-semibold"><option value="applied">Applied</option><option value="under-review">Under review</option><option value="shortlisted">Shortlisted</option><option value="selected">Selected</option><option value="rejected">Rejected</option></select></div></article>; })}{!loading && !filtered.length && <div className="rounded-2xl bg-white p-10 text-center text-sm text-gray-500">No applications found.</div>}</div></div>;
}
