import { useEffect, useState } from "react";
import { FiClipboard, FiMapPin, FiUser } from "react-icons/fi";
import serviceRequestService from "../../services/serviceRequestService";

export default function ServiceRequests() {
  const [requests, setRequests] = useState([]); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const response = await serviceRequestService.getAllServiceRequests(status ? { status } : {}); setRequests(response?.data?.requests || []); } catch (requestError) { setError(requestError.message || "Unable to load service requests."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [status]);
  const update = async (id, nextStatus) => { try { await serviceRequestService.updateServiceRequestStatus(id, nextStatus); await load(); } catch (requestError) { setError(requestError.message); } };
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-[#E87524]">Management</p><h1 className="mt-1 text-2xl font-bold text-[#102A43]">Service Requests</h1><p className="mt-2 text-sm text-gray-500">Review customer building enquiries and update their progress.</p></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-xl border border-gray-200 bg-white px-4 text-sm"><option value="">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="in-progress">In progress</option><option value="completed">Completed</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select>{error && <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="space-y-4">{loading ? <div className="rounded-2xl bg-white p-10 text-center text-sm text-gray-500">Loading requests...</div> : requests.map((request) => <article key={request._id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-[#E87524]"><FiClipboard/></div><div><h2 className="font-bold text-[#102A43]">{request.service}</h2><p className="text-sm text-gray-500">{request.description}</p></div></div><div className="mt-4 flex flex-wrap gap-4 text-xs text-gray-500"><span className="flex items-center gap-1"><FiUser/>{request.customerName || request.user?.name || request.email}</span><span className="flex items-center gap-1"><FiMapPin/>{request.location || "Location not supplied"}</span><span>{request.phone}</span></div></div><select value={request.status} onChange={(event) => update(request._id, event.target.value)} className="h-10 rounded-lg border border-gray-200 bg-gray-50 px-3 text-xs font-semibold"><option value="pending">Pending</option><option value="approved">Approved</option><option value="in-progress">In progress</option><option value="completed">Completed</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select></div></article>)}{!loading && !requests.length && <div className="rounded-2xl bg-white p-10 text-center text-sm text-gray-500">No service requests found.</div>}</div></div>;
}
